# Generated by Django 4.0.4 on 2022-04-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stack', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('live', models.CharField(max_length=100, null=True)),
                ('github', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='public/assets')),
            ],
        ),
    ]
