# Generated by Django 4.0.4 on 2022-04-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliosite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='file',
            new_name='image',
        ),
    ]
